src/App.tsx
src/stores/baseStore.ts
src/supabaseClient.ts
src/types/tables.ts

settings: zustand, immer 세팅

---

package-lock.json
package.json
src/App.tsx
src/components/auth/AuthProvider.tsx
src/components/auth/PrivateRoute.tsx
src/hooks/useAuth.ts
src/pages/GroupPage.tsx
src/pages/MainPage.tsx
src/stores/baseStore.ts

기존 AuthProvider 를 추가합니다.
PrivateRoute 를 통해 로그인된 유저만 접근 가능한 페이지들을 선언합니다.
useAuth 훅과 AuthContext 를 사용하지 않고 useBaseStore 인자에 바로 접근하려고 했는데
Context 의 Provider 부분이 애매해서 일단 상태변수만 useBaseStore 로 가져가고
기존 방식을 차용하였습니다.

settings: AuthProvider 추가

---

src/apis/member.ts
src/apis/prayCard.ts
src/components/KakaoShareBtn.tsx
src/components/member/Member.tsx
src/components/member/MemberList.tsx
src/lib/utils.ts
src/pages/GroupPage.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

MemberList 와 Member 를 이전합니다.
기존 Profile 컴포넌트 명칭이 user.profiles 와 헷갈리는 것 같아 MemberList-Member 구조로 변경하였습니다.

refator: MemberList, Member 컴포넌트 이전

---

package-lock.json
package.json
src/Enums/prayType.ts
src/apis/pray.ts
src/components/member/Member.tsx
src/components/member/MemberList.tsx
src/components/prayCard/PrayCardBtn.tsx
src/components/prayCard/PrayCardCalendar.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/ui/drawer.tsx
src/lib/utils.ts
src/stores/baseStore.ts

기도제목 카드 디테일뷰를 리팩터링 합니다.
시간 관련 이슈 처리 하였고
기존 코드 기반으로 Calendar 와 Btn 코드를 리팩터링 하였습니다.

refactor: 기도제목 카드 디테일뷰

---

src/components/KakaoShareBtn.tsx

카톡 공유하기 기능 오류를 고치고, 두 번 클릭해야 했던 부분을 한 번 클릭해도 되게끔 수정하였습니다.

refactor: 카톡 초대 기능 오류 해결

---

src/App.tsx
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

prayData 또한 PrayCardUI 당 하나씩 전역변수가 필요하기 때문에
prayDataHash 를 통해 관리합니다.
https://www.notion.so/mmyeong/refactor-b59744a5b1ec4726bac1478f3d5b7429?pvs=4

refactor: prayDataHash 구성

---

src/apis/pray.ts
src/components/member/MemberList.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionBtn.tsx
src/stores/baseStore.ts

https://www.notion.so/mmyeong/feat-04826ed7582b45679f9abd7c4c96bb0c?pvs=4

chore: PrayCardUI 분기처리

---

src/components/KakaoShareBtn.tsx
src/pages/GroupPage.tsx
src/pages/MainPage.tsx

https://www.notion.so/mmyeong/fix-kakao-ede01b44d40b4d90a4b57df7bd76bd08?pvs=4

chore: kakao share 관련 수정

---

vercel.json

chore: fix about vercel

---

src/components/prayCard/PrayCardList.tsx
src/components/prayCard/ReactionBtn.tsx
src/lib/utils.ts
src/pages/GroupPage.tsx
src/stores/baseStore.ts

feat: drawer close
fix: sleep util
'오늘의 기도' 에서 기도를 클릭하다가 마지막 기도를 클릭하면 카라셀 및 드로어가 사라지는 기능을 구현했습니다.
그리고 기존의 ReactoinBtn.tsx  파일에서 시간 지연을 위해 정의하였던 sleep 함수를 lib/utils 파일 내에 따로 정의해 두었습니다.

feat: Drawer 닫기

---

src/apis/prayCard.ts
src/components/member/Member.tsx
src/components/prayCard/PrayCardUI.tsx
src/lib/utils.ts
src/stores/baseStore.ts

https://www.notion.so/mmyeong/chore-4f7959ac810646ad945e8d02dd98c800?pvs=4

fix: 긴 기도제목 더보기 처리 + 기도제목 없을 때 수정 안되게끔

---

index.html
src/components/member/MemberList.tsx
src/components/prayCard/PrayCardCreateModal.tsx

focus 되었을 때 확대되어서 나오는 이슈를 해결합니다.

fix: TextArea 줌인 버그 수정

---

src/components/KakaoShareBtn.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/PrayCardUI.tsx
src/pages/GroupPage.tsx

크기나 색의 경우 임의로 지정했습니다. 디자인 시안에 따라 수정하도록 하겠습니다.
https://www.notion.so/mmyeong/feat-x-prayList-blur-a812eb10090c4d6b95cfbf3b434860b6?pvs=4

[feat] 오늘의 기도x → prayList  blur

---

src/components/member/OtherMemberList.tsx
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx

높이 관련 버그와 기도카드 없는 멤버 디테일뷰 무한로딩을 수정합니다.

chore: 높이 버그, 기도카드 디테일 버그 수정

---

src/components/KakaoShareBtn.tsx
src/components/member/Member.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMemberList.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionWithCalendar.tsx
src/lib/utils.ts
src/pages/GroupPage.tsx
supabase/types/database.ts

https://www.notion.so/mmyeong/chore-n-6223bdd5cc984a3190a1342dab50dcf0?pvs=4

chore: 기도제목 날짜 형식 변경 + 내 기도제목 createdAt 제공

---

package.json
src/apis/member.ts
src/components/member/Member.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMember.tsx
src/components/member/OtherMemberList.tsx
src/components/prayCard/PrayCardCreateModal.tsx
src/components/prayCard/PrayCardUI.tsx
src/stores/baseStore.ts
supabase/types/database.ts

https://www.notion.so/mmyeong/refactor-MemberList-PrayCard-a5e5bbc402184b8e8daae460efb2aba7?pvs=4

refactor: Member 업데이트 및 prayCard 없을 때 이슈 해결

---

src/App.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMember.tsx
src/components/member/OtherMemberList.tsx
src/components/prayCard/ReactionWithCalendar.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/components/todayPray/TodayPrayStartCard.tsx
src/pages/GroupPage.tsx
src/stores/baseStore.ts
tailwind.config.js

기도카드가 없을 때 error가 이 부분을 넣기 위해 급하게 pr 넣었습니다.
css 바뀐건 크게 안보셔도 될 것 같아요!

chore: ReactionWithCalendar 수정

---

.github/workflows/deploy_prod.yaml
.gitignore
vercel.json

https://vercel.com/guides/can-you-deploy-based-on-tags-releases-on-vercel
https://www.notion.so/mmyeong/build-PrayU-416e94d41422435b9a1487c9bb7182ce?pvs=4

setting: prod 배포 세팅

---

.github/workflows/deploy_prod.yaml

chore: 배포tag 규칙 수정

---

src/components/KakaoShareBtn.tsx
src/components/todayPray/GroupInviteCard.tsx
src/pages/GroupCreatePage.tsx
src/pages/MainPage.tsx

hotfix: img url 수정

---

package-lock.json
package.json
src/components/GroupMenuBtn.tsx
src/components/prayCard/ReactionBtn.tsx
src/pages/GroupPage.tsx

그룹 아이디가 잘못 입력된 경우 로딩 처리합니다.
그룹 선택 버튼도 없어서 좀 애매하긴 한데 그룹 삭제 기능 들어가거나 요청이 올 때 그룹 404 페이지를 만들면 될 것 같습니다.
+ 로그아웃 추가합니다.

chore: group 라우팅 처리 및 로그아웃 추가

---

src/pages/GroupCreatePage.tsx
src/pages/GroupPage.tsx

최대생성가능 그룹 수 를 4개로 설정했고 4개의 그룹들을 접근가능하며 switching 가능하게 버그 고쳤습니다.
https://www.notion.so/mmyeong/fix-maxGroupCount-faa650adbe594a9ca31b44481dae543c?pvs=4

fix: 최대 생성 가능 그룹수 제한 버그 수정

---

index.html
src/components/GroupMenuBtn.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/todayPray/GroupInviteCard.tsx
src/pages/GroupCreatePage.tsx
src/pages/MainPage.tsx

기본적으로 들어가야 할 사진 기획 하고
storage 에 추가한 사진으로 변경하였습니다.

chore: 랜딩 이미지 수정

---

src/components/member/OtherMember.tsx
src/components/prayCard/PrayCardUI.tsx

fix: 기도 n일 전 수정

---

src/components/KakaoShareBtn.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/PrayCardList.tsx

chore: kakao 버튼 수정

---

index.html
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionBtn.tsx

chore: 리엑션 버튼 그림자 짤림 해결

---

src/App.tsx
src/components/group/LimitGroupCard.tsx
src/components/member/MemberInviteCard.tsx
src/components/prayCard/PrayCardCreateModal.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/components/ui/button.tsx
src/pages/GroupCreatePage.tsx
src/pages/GroupPage.tsx
src/pages/MainPage.tsx

현재 들어가고 있는 모든 이미지 간격 조정 및 Carousel Dots 추가 하였습니다.
https://www.notion.so/mmyeong/fix-Carousel-Dots-408630ed0b5745f5a6d1364ebbf904d5?pvs=4

feat: Carousel Dots 추가

---

src/components/ui/button.tsx

chore: tailwind 커스텀 수정

---

src/components/GroupMenuBtn.tsx
src/pages/MainPage.tsx

로그인 이후에도 메인페이지 접근 가능하도록 하였습니다.
메뉴바에 홈 추가하였습니다. -> 괜찮은지 확인 부탁드립니다.
( 소개, 소개페이지, 홈페이지, 홈화면 등 )
https://www.notion.so/mmyeong/fix-6273eb64b0ae45f6ba7499d558169b1f?pvs=4

chore: mainPage 로그인 후 접근 처리

---

src/components/prayCard/PrayCardCreateModal.tsx
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionWithCalendar.tsx

멘트 수정들이라 코드에서 바뀐 것은 크게 없습니다. 사진 참고해주세요!
아래 사진과 다르게 이모티콘과 글 사이에 띄어쓰기 주었습니다!
https://www.notion.so/mmyeong/chore-34402c0fe84b40b08ac6e5c221e25c6e?pvs=4

chore: 기도제목 헤드라인 추가

---

src/components/member/MyMember.tsx
src/components/member/OtherMember.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/prayCard/ReactionWithCalendar.tsx
src/components/prayCard/WeeklyCalendar.tsx
tailwind.config.js

디자인 시안에 맞춰 간격과 색깔, 그림자 등을 조절하였습니다.
컴포넌트 단위로 작업계속 이어갈 예정입니다.
UI 작업이기 때문에 Preview 로 확인 부탁드립니다!
[Visit Preview](https://vercel.live/open-feedback/prayu-staging-git-fix-ui-detail-visioneers-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)

chore: Member UI 정리

---

src/apis/group.ts
src/apis/member.ts
src/apis/pray.ts
src/apis/prayCard.ts
src/components/GroupMenuBtn.tsx
src/components/group/GroupBody.tsx
src/components/member/MemberInviteCard.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMember.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/share/OpenShareDrawerBtn.tsx
src/components/share/ShareDrawer.tsx
src/pages/GroupPage.tsx

chore: 세부 UI 수정

---

src/App.tsx
src/components/group/GroupMenuBtn.tsx
src/components/share/ShareDrawer.tsx
src/pages/GroupPage.tsx
src/stores/baseStore.ts

페이지 이벤트와 유저 이벤트 분기 처리하고 중복으로 찍히던 버그 수정합니다.
네번씩 찍혔는데 일단 두번씩 찍히도록 했네요ㅋㅋ

fix: 그룹 로딩 문제 수정

---

src/components/member/MyMember.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/PrayCardCreateModal.tsx
src/components/prayCard/PrayCardUI.tsx
src/pages/GroupPage.tsx

버그 상황 - > 해결 이미지
높이 문제로 TextArea 가려지는 버그 계속 나는 것 수정합니다.

fix: 수정뷰 & 기도 넘치는 뷰 수정

---

src/components/member/MyMember.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/pages/GroupCreatePage.tsx

그룹 생성이 실패했을 때 버튼이 계속 비활성화 되어 있는 문제를 해결합니다.
https://www.notion.so/mmyeong/fix-group-efeb86532427427a82ea0a51443220d7?pvs=4

chore: group 생성 문제 처리

---

src/components/group/GroupBody.tsx
src/components/member/MyMember.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/pages/GroupPage.tsx
supabase/types/tables.ts

나에게 온 기도가 MyMember 에서만 불러오고 MyPrayCardUI 에서는 불러오지 않는 문제를 수정합니다.
1. 렌더링 이후 MyMember 에서 기도 총 개수 확인
2. 다른 계정에서 기도해주기
3. 새로고침 안하고 내 기도카드 들어가서 기도 총 개수 확인
https://www.notion.so/mmyeong/fix-4ce4352d02f745e69338be3b0f0a108d?pvs=4

fix: 나에게 온 기도 최신화

---

src/components/member/MyMember.tsx

오늘 기도 해 준 데이터만 따로 가져옵니다!
https://www.notion.so/mmyeong/chore-fbc3d16711dd4260909d74652c4e5804?pvs=4

chore: "오늘" 기도해 준 사람이 있어요

---

src/components/share/ShareDrawer.tsx
src/components/todayPray/TodayPrayBtn.tsx

https://www.notion.so/mmyeong/chore-0a59b508276d4a1eb5f486a66c52c116?pvs=4

chore: 기도 시작하기 버튼 수정 + 링크 공유 amplitude 추가

---

src/components/group/GroupMenuBtn.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/prayCard/ReactionWithCalendar.tsx
src/components/prayCard/WeeklyCalendar.tsx
src/components/todayPray/TodayPrayCardList.tsx
src/stores/baseStore.ts

디테일뷰와 오늘의기도에서 반응 동기화 확인 완료했습니다!!

fix: TodayPrayHash 반영 안되는 이슈 수정

---

src/apis/pray.ts
src/components/prayCard/ReactionBtn.tsx
src/stores/baseStore.ts

한 기도제목 내에서 오늘의 기도 반응을 수정할 수 있게 하였습니다.
https://www.notion.so/mmyeong/feat-pray-8d3f62f93fd249c3a55c69a3056b16d7?pvs=4

feat: pray 반응 바꿀 수 있도록

---

src/components/share/ContentDrawer.tsx
src/components/share/KakaoShareBtn.tsx
src/components/share/OpenContentDrawerBtn.tsx
src/components/todayPray/TodayPrayCardList.tsx
src/lib/utils.ts
src/pages/GroupPage.tsx
src/stores/baseStore.ts

카카오톡으로 공유했을 때의 모습입니다.
https://www.notion.so/mmyeong/feat-225cc343a6264b58a53b6fb3da4ec520?pvs=4

feat: 기도 독려용 공유 컨텐츠-오늘의 말씀

---

src/components/group/GroupBody.tsx
src/components/member/MyMember.tsx
src/components/pray/PrayList.tsx
src/components/pray/PrayListDrawer.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/share/OpenShareDrawerBtn.tsx
src/components/todayPray/TodayPrayCardList.tsx
src/components/todayPray/TodayPrayCardUI.tsx
src/lib/utils.ts

https://www.notion.so/mmyeong/chore-1-2f095b3ab6754b8888c3a2e1321a4130?pvs=4

chore: 기도 안했을 때 오늘의 기도 바로가기 버튼 추가 + 리액션 클릭시 드로워 1개만

---

src/components/group/GroupMenuBtn.tsx
src/stores/baseStore.ts

chore: 그룹 제거 로직 제거

---

src/components/group/GroupBody.tsx
src/components/group/GroupMenuBtn.tsx

chore: text center
add: amplitude 추가사항

chore: text center

---

src/components/group/GroupBody.tsx
src/components/todayPray/TodayPrayCardList.tsx

그룹원 모두 기도제목 만료되었을 때 노출되는 샷입니다.
위에 안내 글씨가 isTodayPray 만 조건이 걸려 있어서 hotfix 수정합니다.
실제로 이미지도 깨지고 있었습니다 제가 이미지 수정하면서 파일을 제거한 것 같습니다.

hotfix: emptyPrayCardList 처리

---

src/components/pray/PrayListDrawer.tsx
src/lib/utils.ts
src/pages/MainPage.tsx

외부 브라우저에 PrayU 에 접근했을 때 
로그인이나 공유 과정에서 앱 전환이 일어나는 문제가 있습니다.
이를 만회하기 위해 로그인 버튼 아래 카카오톡 인앱브라우저 딥링크를 심어놓습니다.
https://www.notion.so/mmyeong/feat-7f385b58246c4045898684689571b231?pvs=4

feat: 카카오 인앱 브라우저 접근

---

src/components/auth/AuthProvider.tsx
src/components/group/GroupBody.tsx
src/components/group/GroupMenuBtn.tsx
src/pages/GroupCreatePage.tsx
src/pages/GroupPage.tsx
src/stores/baseStore.ts

- 현재는 prod에 우리 그리고 제 여자친구까지 총 4명 넣어뒀습니다!
https://www.notion.so/mmyeong/feat-env-fe8fb1215a2347c685a31553b3847219?pvs=4

feat: 프리미엄 유저 with env

---

src/components/pray/PrayList.tsx
src/components/ui/drawer.tsx
src/components/ui/sheet.tsx
src/lib/utils.ts

오늘 기도한 반응에 노란색 테두리 추가했습니다.
https://www.notion.so/mmyeong/36e5f9ba216f48d0a0efb2e204b98e8a?pvs=4

feat: 오늘 기도 테두리 추가

---

src/App.css
src/components/prayCard/PrayCardCreateModal.tsx

너무 많은 정보가 들어가고 있는 것 같으면 말씀해주세용!
https://www.notion.so/mmyeong/design-c071e9be992945b9aa475b57f7b5d8ed?pvs=4

design: 기도 생성 뷰 수정

---

src/components/prayCard/PrayCardCreateModal.tsx

고정 안하면 안드로이드에서 textArae 가 줄어드는 이슈가 있어 수정합니다.

fix: PrayCard 생성뷰 height 고정

---

src/components/prayCard/MyPrayCardUI.tsx

내 기도제목에서 textArea가 작아지는 이슈를 수정합니다.

fix: MyPrayCard height 이슈 수정

---

.github/workflows/deploy_prod.yaml

https://www.notion.so/mmyeong/Dev-e81515e443f04572919bf048fb9ec1a1?pvs=4

build: ci/cd 전략 수정

---

.github/workflows/deploy_prod.yaml
package-lock.json
package.json
src/analytics/analytics.ts
src/components/group/GroupBody.tsx
src/stores/baseStore.ts
src/vite-env.d.ts
vite.config.ts

1. 수동으로 tag release 하는 과정에서 버전은 자동으로 관리되도록 수정합니다.
`이전` 태그가 push 될 때 배포
`이후` release 노트가 published 된 이후 배포 -> npm version patch 커밋 main에 push(다음버전 tag 생성)
2. version 정보를 이벤트와 센트리 유저정보에 추가합니다.
1. CI/CD
Test-Ci 레포를 만들고 테스트 진행
https://github.com/TeamVisioneer/Test-Ci/actions
2. 이벤트 처리
Amplitude staging 에서 익명유저와 로그인 유저 이벤트 병합처리 확인
버전 프로퍼티 확인

settings: 버전 업데이트 관리

---

package-lock.json
package.json
src/App.tsx
src/analytics/analytics.ts
src/analytics/googleAnalytics.d.ts

https://www.notion.so/mmyeong/feat-UTM-ad0fa363a8f84c298c9edba040766297?pvs=4
https://www.notion.so/mmyeong/feat-GA-73c034d31cd941c59e1bb18886d9243d?pvs=4
utm을 생성해서 App.tsx 파일에서 '페이지 메인'이벤트의 속성으로 넣었습니다.
구글 애널리틱스를 analytics 에 추가했고 필요 타입을 별도의 파일로 저장하였습니다.
관련 환경 변수는 우선 staging에만 제가 세팅해놓겠습니다. 왜냐하면 구글 애널리틱스 계정에 staging프로젝트만 생성해두었기 때문입니다.
merge 후 팀원 간 검수를 통해 prod 용 프로젝트와 환경변수를 즉시 세팅해놓도록 하겠습니다.

feat: GA 추가 && utm 추가

---

src/components/member/MyMember.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/pages/GroupCreatePage.tsx
src/pages/PrayCardCreatePage.tsx

1. 기도카드 Textarea 클릭시 수정하기
2. group 생성할 때 기도카드 content 기본값 ""  로 넣기
-> 프론트에서 보여줄 때 "✏️ 기도카드를 작성해주세요" 예외처리 하기
3. navigation -> location.replace 변경
https://www.notion.so/mmyeong/update-4dc590686f1c48fdb2ae1b1cd480f9ea?pvs=4

fix: 기도카드 작성 디폴트값 수정

---

src/components/group/GroupBody.tsx
src/components/prayCard/OtherPrayCardUI.tsx

그룹 참여가 안되는 버그를 수정합니다. memberList 예외처리 추가

fix: 그룹 참여 버그 수정

---

.github/workflows/deploy_prod.yaml
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx

hotfix: PrayCardUI 예외처리

---

src/components/prayCard/MyPrayCardUI.tsx

fix: 내 기도제목 수정 TextArea 변경

---

package.json
src/components/prayCard/MyPrayCardMoreBtn.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/ui/dropdown-menu.tsx
src/components/ui/textarea.tsx
src/components/ui/use-toast.ts
tsconfig.app.json
yarn.lock

나중에 차단하기 또는 신고하기를 하기 위해서는 더보기 버튼이 있어야할 것 같습니다.
오른쪽은 "삭제하기" 눌렀을 때 (아직 기능은 없지만 삭제하기 기능을 바로 추가할 것 같아서 미리 만들어두었습니다.)
https://www.notion.so/mmyeong/feat-8e76537ce8814ddbb5229fe3ed89c21d?pvs=4

feat: 내 기도제목 > 더보기 추가

---

src/components/prayCard/MyPrayCardMenuBtn.tsx
src/components/prayCard/MyPrayCardUI.tsx

내 기도제목을 삭제시키는 기능을 만들었습니다.
https://www.notion.so/mmyeong/feat-3e105ef0e0c2417bb1a46ab91610d263?pvs=4

feat: 내기도카드 삭제 alert 추가

---

src/components/notice/OpenEventDialogBtn.tsx
src/components/ui/dialog.tsx

https://www.notion.so/mmyeong/feat-dad41238f5174d8b9fbc33d01366ed37?pvs=4

feat: 공지 다이얼로그 백키 반응 추가

---

src/App.tsx
src/apis/member.ts
src/apis/prayCard.ts
src/apis/profiles.ts
src/components/kakao/Kakao.d.ts
src/components/kakao/KakaoCallback.tsx
src/components/kakao/KakaoController.tsx
src/components/kakao/KakaoTokenRepo.ts
src/components/prayCard/ReactionBtn.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/components/todayPray/TodayPrayCardList.tsx
src/components/ui/use-toast.ts
src/stores/baseStore.ts
supabase/types/database.ts

기도 반응 클릭시 카카오톡 메세지가 전송되도록 구현합니다.
<br />
-> 카카오톡 내에서도 심사가 필요합니다. 본 심사는 친구목록을 선택하는 방식으로 먼저 패스시킬 예정입니다.
---
https://www.notion.so/mmyeong/feat-a0b3153dee3a4868b7ca18fd4f8ff935?pvs=4

feat: 기도 반응 클릭시 알림 구현

---

src/apis/user.ts

fix: deleteUser url 하드코딩 수정

---

src/apis/member.ts
src/apis/profiles.ts
src/components/alert/ReportAlert.tsx
src/components/kakao/KakaoCallback.tsx
src/components/member/OtherMemberList.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx
src/components/prayCard/OtherPrayCardMenuBtn.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/todayPray/TodayPrayCardUI.tsx
src/pages/GroupPage.tsx
src/pages/MyProfilePage.tsx
src/stores/baseStore.ts
supabase/types/database.ts

Profiles 에 blocking_users 필드를 추가하고 차단 유저를 관리합니다.
기도카드 메뉴버튼의 차단 기능을 구현합니다.
차단한 유저 관리 및 게시물 가리기는 이어지는 작업에서 진행합니다.

feat: 차단 기능 추가

---

package.json
src/App.tsx
src/components/ui/checkbox.tsx
src/pages/MainPage.tsx
src/pages/TermServicePage.tsx

https://www.notion.so/mmyeong/setting-dd7fb746bf63436f8dda06da7bdb4195?pvs=4

feat: 서비스 이용 약관 동의 페이지 추가

---

src/apis/member.ts
src/components/group/GroupMenuBtn.tsx
src/components/kakao/KakaoInit.tsx
src/components/kakao/KakaoTokenRepo.ts
src/components/prayCard/ReactionBtn.tsx
src/stores/baseStore.ts

기존에는 userId-groupId 의 유니크 키 때문에 동일유저가 동일 그룹에 새로운 멤버로 들어올 수 없는 버그가 있었습니다.
멤버가 그룹을 나간 후 재입장이 가능하도록 수정합니다.

fix: 그룹 재입장 버그 수정

---

package-lock.json
src/components/notice/EventDialog.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/todayPray/TodayPrayBtn.tsx

fix: 카카오 메세지 임시 철회

---

src/pages/MyProfilePage.tsx

카카오 메세지가 철회되면서 관련 환경설정 부분도 가립니다.

hotfix: 환경설정 가리기

---

src/components/prayCard/ReactionBtn.tsx

hotfix: 오늘의 기도 스와이프 버그 수정

---

src/components/alert/ConfirmAlert.tsx
src/components/group/GroupMenuBtn.tsx
src/components/kakao/Kakao.d.ts
src/components/kakao/KakaoController.tsx
src/components/kakao/KakaoMessage.ts
src/components/prayCard/MyPrayCardMenuBtn.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/stores/baseStore.ts

hotfix: 기도요청 메세지 수정

---

src/components/group/GroupMenuBtn.tsx
src/components/prayCard/MyPrayCardMenuBtn.tsx
src/components/prayCard/OtherPrayCardMenuBtn.tsx
src/pages/MyProfilePage.tsx
src/stores/baseStore.ts

버튼 색 동적으로 수정하면서 반영되지 않은 이슈 처리합니다.

hotfix: Alert 창 버튼 색 이슈

---

src/components/auth/PrivateRoute.tsx
src/components/group/GroupMenuBtn.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMemberList.tsx
src/components/pray/PrayList.tsx
src/components/pray/PrayListDrawer.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/todayPray/TodayPrayCardListDrawer.tsx
src/components/ui/drawer.tsx
src/pages/GroupCreatePage.tsx
src/pages/GroupPage.tsx
src/pages/MyProfilePage.tsx

1. 드로워에 x 버튼 추가했습니다.
3. 수정모드에서 완료 버튼을 추가하였습니다.

hotfix: 드로워 exit 버튼 추가

---

src/components/prayCard/DeletedPrayCardUI.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx

hotfix: 만료카드, 삭제카드 예외처리

---

src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx

카드 로딩 높이 조정 부분을 제가하면서 생긴 이슈를 해결합니다.

hotfix: otherMemberList 카드 로딩 UI

---

src/components/ui/button.tsx

다음에 작성하기 색상을 수정했습니다.
text black -> text -[#222222]

fix: 다음에 작성하기 색상 수정

---

src/apis/user.ts
src/pages/MyProfilePage.tsx

로그아웃 -> 탈퇴
에서 
탈퇴 -> 로그아웃
으로 순서 변경했습니다.
https://www.notion.so/mmyeong/refactor-f3f9a5b2d89c49a784955d18fa50a9e3?pvs=4

fix: 회원탈퇴 후 로그아웃 진행

---

src/App.css
src/pages/MainPage.tsx

chore: 이미지 로딩처리

---

src/App.tsx
src/analytics/analytics.ts
src/components/auth/AppleLoginBtn.tsx
src/components/auth/EmailLoginBtn.tsx
src/components/auth/KakaoLoginBtn.tsx
src/components/notice/EventDialog.tsx
src/components/todayPray/TodayPrayOnboardingList.tsx
src/stores/baseStore.ts

이벤트를 추가할 때는 기존에 만들어둔
analyticsTrack 를 추가합니다.
analytics.track 는 외부에서 import 해서 사용하지 못하도록 export 를 제거하였습니다.
(analytics.track 를 사용할 경우 analyticsTrack 에서 정의한 superProperty 적용이 되지 않습니다.)

chore: 이벤트 처리 수정

---

src/App.tsx
src/analytics/analytics.ts
src/components/auth/AppleLoginBtn.tsx
src/components/auth/EmailLoginBtn.tsx
src/components/auth/KakaoLoginBtn.tsx
src/components/group/GroupMenuBtn.tsx
src/components/member/MyMember.tsx
src/components/notice/EventDialog.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/todayPray/TodayPrayOnboardingList.tsx
src/pages/GroupRedirectPage.tsx
src/pages/PrayCardCreatePage.tsx
src/pages/TermServicePage.tsx
src/stores/baseStore.ts

서비스 약관 동의를 누를 경우 그룹이 바로 생성되도록 합니다.
"00 의 그룹"

update: 그룹 바로 생성

---

src/components/todayPray/TodayPrayCardListDrawer.tsx
src/components/todayPray/TodayPrayCardUI.tsx

https://www.notion.so/mmyeong/feat-23148dff2eea4f0487e9ecd024d63906?pvs=4

feat: 오늘의 기도 카운트 &&  텍스트 위치 수정

---

src/apis/group.ts
src/components/group/GroupMenuBtn.tsx
src/components/group/GroupSettingsDialog.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMemberList.tsx
src/components/ui/dialog.tsx
src/components/ui/input.tsx
src/pages/GroupPage.tsx
src/stores/baseStore.ts

그룹장이 그룹명을 수정할 수 있는 모달을 추가합니다.
설정 탭은 그룹장만 볼 수 있도록 구성합니다.

feat: 그룹 수정 모달 추가

---

src/components/prayCard/DummyPrayCardUI.tsx
src/components/prayCard/DummyReactionWithCalendar.tsx
src/components/todayPray/TodayPrayCardDummyList.tsx
src/components/todayPray/TodayPrayOnboardingList.tsx

https://www.notion.so/mmyeong/chore-1c2dfbdc99cc42a9963cabeed94a1194?pvs=4

chore: dummyCalendar 과거날짜 기도채워놓기

---

src/components/group/GroupMenuBtn.tsx
src/components/group/GroupSettingsDialog.tsx
src/components/member/MyMember.tsx
src/components/member/MyMemberBtn.tsx
src/components/member/OtherMember.tsx
src/components/notice/OpenEventDialogBtn.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/share/OpenContentDrawerBtn.tsx
src/components/share/OpenShareDrawerBtn.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/components/ui/drawer.tsx

드로워 클릭 할 때 pushState 를 통해 현재 url 넣는 작업을 onClick 각각 에 넣었었는데
이렇게 하면 Drawer 생성할 때마다 까먹기 때문에 Drawer 내에서 관리합니다.

fix: 드로워 백키 pushState 전역 적용

---

src/components/share/ContentDrawer.tsx

말씀 공유 컨텐츠를 31개 (1달치) 로 확장하였습니다!

chore: 말씀 컨텐츠 31개로 확장

---

package-lock.json
package.json
src/components/auth/LogInDrawer.tsx

update: 로그인 뷰 수정

---

package-lock.json
package.json
src/pages/MainPage.tsx
src/pages/MainPage/MainHeader.tsx

튜토리얼로 인해 로그인 과정에 악영향이 발생하여 제거합니다.

update: 로그인전 튜토리얼 제거

---

src/components/prayCard/DummyReactionWithCalendar.tsx
src/components/prayCard/WeeklyCalendar.tsx
src/lib/utils.ts

https://www.notion.so/mmyeong/chore-a85469bf0f87448ba4d6f8bbc148e49c?pvs=4

chore: calendar 요일로 변경

---

src/components/prayCard/DummyPrayCardUI.tsx
src/components/prayCard/DummyReactionWithCalendar.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/todayPray/TodayPrayCardUI.tsx
src/components/todayPray/TodayPrayCompletedItem.tsx

update: 기도반응 버튼 효과 업데이트

---

package-lock.json
package.json

hotfix: 0.2.5

---

src/pages/MainPage/MainHeader.tsx
src/pages/StoryPage/StoryPage.tsx

https://www.notion.so/mmyeong/feat-f4b488ec04884bf5bf6611418e4d5365?pvs=4

chore: 랜딩페이지 상단 바 추가

---

src/components/todayPray/TodayPrayCardDummyList.tsx
src/components/todayPray/TodayPrayDummyCompletedItem.tsx

update: 온보딩 완료뷰 변경

---

src/components/member/OtherMemberList.tsx
src/components/notice/InviteBanner.tsx
src/pages/GroupPage.tsx
tailwind.config.js

feat: 초대 베너 추가

---

src/components/member/MyMember.tsx
src/components/member/OtherMember.tsx
src/components/member/OtherMemberDrawer.tsx
src/components/member/OtherMemberList.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/prayCard/ReactionWithCalendar.tsx
src/components/share/KakaoShareBtn.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/components/todayPray/TodayPrayCardList.tsx
src/components/todayPray/TodayPrayCardUI.tsx
src/components/todayPray/TodayPrayInviteCompletedItem.tsx
src/components/todayPray/TodayPrayStartCard.tsx

기도 반응 이벤트의 속성에 memberList.lenght 정보를 추가합니다.
memberList.lenght 2 이상인 반응을 유의미한 반응으로 판단합니다.
추가로 드로워 버그 관련 수정사항 반영합니다.

chore: 기도반응 및 오늘의 기도 이벤트 수정

---

src/App.tsx
src/components/auth/KakaoLoginBtn.tsx
src/components/auth/LogInDrawer.tsx
src/components/auth/LoginRedirect.tsx
src/components/kakao/Kakao.d.ts
src/components/kakao/KakaoCallback.tsx
src/lib/utils.ts
src/pages/PrayCardCreatePage.tsx
src/pages/TermServicePage.tsx
src/pages/TutorialPage.tsx

이제 웹&앱에서도 카카오 로그인하면 카카오톡이 실행이 됩니다.
(안드로이드는 테스트중)
edge function을 쓰지 않았고 client에서 해결하도록 간단하게 만들었습니다.
자세한 내용은 코멘트 달아두었습니다!
https://www.notion.so/mmyeong/feat-bf926b3955c24a7893cb6783bada2bd4?pvs=4

feat: add 카카오앱으로 로그인

---

src/components/prayCard/DummyReactionWithCalendar.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/components/todayPray/TodayPrayCardList.tsx

오늘의 기도 시작버튼, 기도반응 버튼에 멤버 총원 정보를 포함합니다.
이벤트가 들어가고 있지 않아서 수정합니다.

hotfix: total-member 이벤트 추가

---

src/App.tsx
src/components/member/OtherMember.tsx
src/components/prayCard/DummyPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/components/todayPray/TodayPrayCardList.tsx
src/pages/TermServicePage.tsx
src/pages/TutorialPage.tsx
src/stores/baseStore.ts

hotfix: tutorial 사파리 뷰 버그 & 드로워 버그

---

src/apis/user.ts
src/components/auth/LoginRedirect.tsx
src/stores/baseStore.ts

hotfix: 유저 메타데이터 업데이트

---

src/components/kakao/KakaoCallback.tsx
src/components/kakao/KakaoTokenRepo.ts
src/components/prayCard/MyPrayCardMenuBtn.tsx

session.provider_access_token 이 부분 제거하면서
기도 요청 부분도 kakao callback 으로 오도록 변경합니다.

refactor: 기도요청 리팩터링

---

src/apis/profiles.ts
src/components/auth/LoginRedirect.tsx
src/global.d.ts
supabase/types/database.ts

flutter에서 localStorage에 저장한 fcm_token을 받고 updateProfiles를 합니다.
앱 수정사항은 아래 링크에서 확인하실 수 있습니다!
https://github.com/TeamVisioneer/PrayU-WebView/pull/17
https://www.notion.so/mmyeong/feat-fcm_token-5ff9bd484ad94935a9d0c96ccb6e1907?pvs=4

feat: fcm token local storage 받기 + updateProfiles

---

src/App.tsx
src/apis/notification.ts
src/components/kakao/KakaoTokenRepo.ts
src/components/notification/NotificationBtn.tsx
src/components/notification/NotificationList.tsx
src/pages/GroupPage.tsx
src/stores/baseStore.ts

fix: kakao.auth 예외처리

---

package-lock.json
src/components/notice/EventDialog.tsx
src/components/notification/NotificationBtn.tsx
src/components/notification/NotificationItem.tsx
src/components/notification/NotificationList.tsx
src/components/ui/dialog.tsx
src/components/ui/popover.tsx
src/components/ui/sheet.tsx
src/stores/baseStore.ts

feat: 공지알림 dialog 추가

---

src/App.tsx
src/apis/group.ts
src/apis/profiles.ts
src/pages/AdminPage/AdminPage.tsx
src/pages/AdminPage/NotificationDialog.tsx
src/stores/baseStore.ts

Admin 페이지를 추가합니다.
공지사항 알림을 추가하는 상황이 있기 때문에 본 기능을 admin 페이지에 넣어둡니다.
추가로 간단한 지표들 넣어두었습니다.

feat: 어드민 페이지 추가

---

src/App.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/pages/Open/UnionWorshipPage.tsx

1027 연합예배 특별 기도방 페이지 가안 배포합니다.

feat: 1027 Union Page

---

src/components/auth/LogInDrawer.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/pages/GroupPage.tsx
src/pages/Open/UnionWorshipPage.tsx
src/pages/PrayCardCreatePage.tsx

https://www.notion.so/mmyeong/feat-1027-union-3936e0f77d564824858535e3d39cf420?pvs=4

feat: 1027 union login

---

src/apis/member.ts
src/components/group/GroupHeader.tsx
src/components/member/OtherMember.tsx
src/components/member/OtherMemberList.tsx
src/pages/GroupPage.tsx
src/pages/Open/UnionWorshipPage.tsx
src/stores/baseStore.ts

feat: Member 페이지네이션
refactor: 멤버 페이지네이션

feat: Member 페이지네이션

---

src/apis/prayCard.ts
src/components/todayPray/TodayPrayCardList.tsx
src/components/todayPray/TodayPrayCardListDrawer.tsx
src/pages/Open/HookingDialog.tsx
src/pages/Open/HookingItem.tsx
src/pages/Open/UnionWorshipPage.tsx

오늘의 기도 드로워 닫히면 내 그룹 만들기 모달 뜨도록 합니다.

feat: 내 그룹 만들기 모달 팝업

---

src/components/profile/PrayCardHistoryList.tsx
src/pages/MyProfilePage.tsx

https://www.notion.so/mmyeong/98f9593602f6406d9c70a5bacfa4cdab?pvs=4
feat: 상단 고정
feat: 상단 수정
fix: 태그 글자크기 변경

feat: 히스토리 상단 고정

---

package-lock.json
package.json
src/components/prayCard/MyPrayCardUI.tsx
src/components/profile/PrayCardHistoryList.tsx
src/components/profile/PrayCardHistoryPrayList.tsx
src/components/profile/PrayCardHistoryUI.tsx
src/components/profile/SettingDialog.tsx
src/pages/MyProfilePage.tsx
tailwind.config.js

현재 UI 는 깨지는 부분도 많고 기존 UI 들과 다른 느낌이라 기존 UI 느낌으로 대체합니다.

refactor: PrayCard History 수정

---

src/components/auth/AppleLoginBtn.tsx
src/components/auth/EmailLoginBtn.tsx
src/components/auth/KakaoLoginBtn.tsx
src/components/auth/LogInDrawer.tsx

우리의 의도와는 다르게 앱에서 애플, 이메일 로그인이 꽤 있어서,
다른 방법으로 로그인으로 좀 작게 만들어주었습니다.
https://www.notion.so/mmyeong/refactor-7135694e87454bd6b2d976da63a4a3cd?pvs=4

refactor: 다른 방법으로 로그인

---

src/components/profile/PrayCardHistoryDrawer.tsx

앞으로 기도카드 히스토리처럼 드로어가 올라갈 것이 병렬적으로 많이 있는 드로어에만 선택적으로 onClose를 달아주면 될듯합니다.
https://www.notion.so/mmyeong/ae8e62dd9acb4379a6fdac8c622655f8?pvs=4

feat: PrayCardHistoryDrawer onClose 추가

---

src/components/todayPray/TodayPrayCardUI.tsx
src/pages/TutorialPage.tsx

1. 오늘의 기도에서 비어있는 내 기도제목을 누를 경우 내 기도제목 드로어로 바로갑니다.
2. 튜토리얼에서 다음을 누를때 반응 버튼을 안누르면 누른 엑션을 거치고 갑니다.

chore: 내 기도작성 바로가기

---

src/components/prayCard/DummyReactionWithCalendar.tsx
src/components/prayCard/WeeklyCalendar.tsx
src/components/profile/SettingDialog.tsx
src/components/todayPray/TodayPrayStartCard.tsx
src/pages/TutorialPage.tsx

1. 튜토리얼 인덱스 깨짐 수정
2. 반응 캘린더 깨짐 수정
-> div 테두리를 img 테두리로 변경

hotfix: 튜토리얼 인덱스 수정 && 캘린더 테두리 수정

---

package-lock.json
package.json
src/App.css
src/App.tsx
src/apis/openai.ts
src/pages/QuietTimePage.tsx

<table>
<tr>
<td>QT 생성 전</td>
<td>QT 로딩 중</td>
<td>QT 생성 완료</td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/9b1a841d-f046-4664-8aa0-5b83b74a3cc8" width="200"></td>
<td><img src="https://github.com/user-attachments/assets/b39d5ab1-765f-489f-92c8-8ff0514a4fdd" width="200"></td>
<td><img src="https://github.com/user-attachments/assets/34fd079c-1243-4b5c-b45f-3e5c04dbd6f6" width="200"></td>
</tr>
</table>
- 프롬프트 예시
```dart
내가 지정한 성경 본문과 다음 지시에 따라 20-30대 크리스천을 위한 QT를 JSON 형식으로 작성해 주세요.
성경 본문이 잘못되었으면 잘못되었다고 한글로 json 형태로 출력해줘
- 성경 본문: 안녕하세요
- 내용 구성:
- "scripture": 성경 본문 텍스트와 출처
- "meditation": 간단한 묵상 내용으로, 20-30대가 이해하기 쉽게 표현된 도입부와 주요 메시지 3가지 (각 메시지에 소제목과 간단한 설명 포함)
- "application_questions": 20-30대 크리스천의 삶과 밀접하게 관련된 최신 상황과 함께 사회적 문제에 공감할 수 있는 3개의 적용 질문. 행동으로 유도할 수 있는 질문. …
```

feat: QT 페이지 생성

---

src/apis/bible.ts
src/apis/openai.ts
src/lib/utils.ts
src/pages/BibleCardPage/BibleCardPage.tsx
src/stores/baseStore.ts
supabase/types/database.ts
supabase/types/tables.ts

GPT 로 생성한 말씀은 정확한 워딩의 말씀을 주지 않기 때문에 DB 에서 가져오도록 반영합니다

refactor: bible card API 수정 내용 반영

---

src/pages/QuietTimePage.tsx

1. 창세기 9:9
2. 창세기 9장 9절
3. 시편 9편 9절
4. (범위) 창세기 9:9-10 (~도 가능)
5. (범위) 창세기 9장 9절 ~ 10절

feat: QT 생성시 말씀 DB로 input 체크 + 출력

---

src/components/profile/PrayCalendar.tsx

https://www.notion.so/mmyeong/chore-css-7f0b32a9c2414696a5e3f777410fdc73?pvs=4

chore: aspect 제거

---

src/components/notice/WeekUpdateDialog.tsx
src/pages/AdminPage/AdminPage.tsx
src/pages/AdminPage/NotificationDialog.tsx

신고가 들어온 게시물을 필요에 따라 admin 에서 삭제 처리 합니다.

refactor: 어드민 기도제목 삭제 기능

---

src/apis/bible.ts
src/apis/openai.ts
src/lib/utils.ts
src/pages/BibleCardPage/BibleCardFlip.tsx
src/pages/QuietTimePage.tsx
src/stores/baseStore.ts

로그를 저장하기 위해 수정이 필요한 부분을 변경합니다.
여러 구절도 말씀 노출 되도록 변경
qtData 조회 후
있으면 → 사용
없으면 → openai 요청

refactor: QT data fetching 리팩터링

---

src/apis/qt_data.ts
src/pages/QuietTimePage.tsx
src/stores/baseStore.ts
supabase/types/database.ts
supabase/types/tables.ts

오늘의 QT를 qt_data 테이블에 저장하도록 하였습니다.
https://www.notion.so/mmyeong/feat-QT-DB-a31ca7acf43743dab9b3e1ed018b84d9?pvs=4

feat: Qt 데이터 저장

---

src/pages/BibleCardPage/BibleCardFlip.tsx
src/pages/BibleCardPage/BibleCardGeneratorPage.tsx
src/pages/BibleCardPage/BibleCardPage.tsx
src/pages/BibleCardPage/BibleCardUI.tsx

chore: 말씀카드 포지션 수정

---

src/pages/BibleCardPage/BibleCardFlip.tsx
src/pages/TermServicePage.tsx

말씀카드 생성한 사용자가 회원가입 했을 때 mymember.summary 업데이트 합니다.

hotfix: BibleCard 유저 PraySummary 관리

---

src/components/todayPray/TodayPrayCompletedItem.tsx
src/pages/QuietTimePage.tsx

지금은 멘트가 "내용에 문제가 있나요?" 인데 다른 멘트도 편하게 알려주세요!
https://www.notion.so/mmyeong/feat-QT-e79066dcf14b4815955285830f8a349f?pvs=4

hotfix: QT 신고하기

---

src/components/member/MyMember.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/lib/utils.ts
src/pages/GroupPage.tsx

기도카드를 갱신하는 과정에서 계속 생성페이지로 넘어오는 문제를 수정합니다.

hotfix: 기도카드 갱신 버그 수정

---

src/components/auth/LoginRedirect.tsx
src/types/global.d.ts

로그인할 때 flutter webview 에 이벤트를 보내서 userId 를 set 할 수 있도록 합니다.

build: Onesignal 로그인 이벤트 처리

---

src/apis/notification.ts
src/apis/onesignal.ts
src/components/notification/NotificationList.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/profile/SettingDialog.tsx
src/pages/PrayCardCreatePage.tsx
src/stores/baseStore.ts

feat: onesignal push 업데이트
feat: 모두읽음, ui 개선

feat: onesignal push 업데이트

---

src/App.tsx
src/components/member/MyMember.tsx
src/components/prayCard/MyPrayCardMenuBtn.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/PrayCardEditPage.tsx

update: PrayCard 수정 페이지

---

src/App.tsx
src/AppInit/AppInit.tsx
src/components/auth/LogInDrawer.tsx
src/pages/BibleCardPage/BibleCardFlip.tsx
src/stores/baseStore.ts

- userAgent 에서 App 관련 커스텀 키를 핸들링합니다.
- 푸시 알림 핸들링을 위해 이벤트 처리 로직을 추가합니다.

feat: App init 컴포넌트 추가

---

package-lock.json
package.json
src/components/prayCard/PrayCardEditPage.tsx
src/components/todayPray/TodayPrayCardUI.tsx
src/components/ui/sheet.tsx

- 내 기도카드를 누를 때 수정페이지에서 바로 커서가 잡히도록 수정합니다.
- 좌측 메뉴시트가 뒤로가기할 때 다시 노출되는 문제를 수정합니다.

hotfix: 내 기도카드수정 페이지 연결

---

package-lock.json
package.json
src/App.tsx
src/AppInit/AppInit.tsx
src/apis/member.ts
src/components/group/GroupHeader.tsx
src/components/group/GroupListDropDown.tsx
src/components/group/GroupListHeader.tsx
src/components/group/GroupMemberProfileList.tsx
src/components/group/GroupMenuBtn.tsx
src/components/group/GroupSettingsDialog.tsx
src/components/profile/UserProfile.tsx
src/components/share/OpenShareDrawerBtn.tsx
src/components/todayPray/TodayPrayCompletedItem.tsx
src/components/ui/select.tsx
src/components/ui/sheet.tsx
src/pages/GroupPage.tsx
src/pages/GroupRedirectPage.tsx
src/pages/MyProfilePage.tsx
src/pages/Open/UnionWorshipPage.tsx
src/pages/PrayCardCreatePage.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

feat: Group 리스트뷰 페이지 추가

---

package-lock.json
package.json
src/components/notice/WeekUpdateDialog.tsx
src/components/ui/dialog.tsx

fix: 다이얼로그 수정

---

src/components/group/GroupMenuBtn.tsx
src/components/member/OtherMemberList.tsx
src/components/member/useRealtimeMember.ts
src/components/notice/WeekUpdateDialog.tsx
src/components/notification/NotificationBtn.tsx
src/components/notification/useRealtimeNotification.ts
src/components/ui/sheet.tsx
src/pages/PrayCardCreatePage.tsx

Supabase 의 realtime 기능을 활용하여 Notification 과 Member 테이블의 Insert 이벤트를 핸들링합니다.
update: 실시간 알림 카운트 반영
chore: 문의사항 버튼 변경
update: 실시간 멤버 추가 반영

update: 실시간 알림 카운트 및 멤버초대 반영

---

src/components/group/GroupListDrawer.tsx
src/components/group/GroupMenuBtn.tsx
src/components/notification/NotificationItem.tsx
src/pages/GroupListPage.tsx
src/pages/MainPage.tsx
src/pages/MainPage/DownloadBanner.tsx
src/pages/StoryPage/StartPrayUBtn.tsx
src/pages/StoryPage/StoryPage.tsx

- 다운로드 베너 추가 ( 스토리 페이지, 메인 페이지 )
- 그룹리스트 페이지 알림 fetching 및 기타 버그 수정

hotfix: 다운로드 베너 추가

---

src/AppInit/AppInit.tsx
src/components/prayCard/PrayCardEditPage.tsx
src/pages/PrayCardCreatePage.tsx

This reverts commit 75aaee66881a312fa025319648ca7b3b68f4306e.

hotfix: 기도카드 생성 페이지 스크롤 버그 수정 Revert

---

package-lock.json
package.json
src/App.tsx
src/AppInit/AppInit.tsx
src/apis/churchApiService.ts
src/components/office/ChurchCard.tsx
src/components/office/ChurchSearch.tsx
src/components/office/CommunityForm.tsx
src/components/office/GroupCard.tsx
src/data/mockOfficeData.ts
src/pages/Office/AddCommunityPage.tsx
src/pages/Office/ChurchDetailPage.tsx
src/pages/Office/ChurchSearchPage.tsx
src/pages/Office/CommunityDetailPage.tsx
src/pages/Office/GroupDetailPage.tsx
src/pages/Office/MyChurchesPage.tsx
src/pages/Office/MyCommunityPage.tsx
src/pages/Office/OfficePage.tsx
src/pages/Office/index.ts
src/stores/officeStore.ts

feat: PrayU Office 교회공동체 기능 UI

---

package-lock.json
package.json
src/pages/Office/CommunityDetailPage.tsx
src/pages/Office/GroupDetailPage.tsx

feat: UI 및 구성 업데이트
feat: PDF 저장 기능

feat: UI 및 구성 업데이트

---

package-lock.json
package.json
src/apis/group.ts
src/components/group/GroupListDrawer.tsx
src/components/group/GroupListHeader.tsx
src/components/member/OtherMemberList.tsx
src/components/profile/PrayCardHistoryDrawer.tsx
src/components/profile/PrayCardHistoryList.tsx
src/components/profile/SettingDialog.tsx
src/components/share/KakaoShareBtn.tsx
src/components/ui/tooltip.tsx
src/pages/GroupListPage.tsx
src/pages/Office/OfficePage.tsx
src/pages/Office/UnionDetailPage.tsx
supabase/types/tables.ts

feat:  공동체 그룹 등록 카카오 메세지
refactor: 내 프로필에 말씀카드 표시

feat:  공동체 그룹 등록 카카오 메세지

---

src/App.tsx
src/components/auth/LogInDrawer.tsx
src/components/group/GroupListDrawer.tsx
src/components/group/GroupMenuBtn.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMemberDrawer.tsx
src/components/notice/BannerDialog.tsx
src/components/notice/EventDialog.tsx
src/components/notice/ExternalLinkDialog.tsx
src/components/notice/WeekUpdateDialog.tsx
src/components/pray/PrayListDrawer.tsx
src/components/profile/PrayCardHistoryDrawer.tsx
src/components/profile/PrayCardHistoryPrayListDrawer.tsx
src/components/profile/SettingDialog.tsx
src/components/share/ShareDrawer.tsx
src/components/todayPray/TodayPrayCardListDrawer.tsx
src/components/ui/dialog.tsx
src/pages/BibleCardPage/BibleCardFlip.tsx
src/pages/PrayCardCreatePage.tsx
src/stores/baseStore.ts

fix: 기도카드 임시저장되도록 수정
fix: 드로워 버그 수정
fix: 다이얼로그 버그 수정
fix: 기도카드 예외처리 수정

fix: 기도카드 임시저장되도록 수정

---

src/apis/office/groupController.ts
src/components/todayPray/TodayPrayBtn.tsx
src/pages/Office/UnionJoinPage.tsx

hotfix: Office 그룹 필터 수정
hotfix: 이중드로워 버그 수정

hotfix: Office 그룹 필터 수정

---

src/App.tsx
src/apis/profiles.ts
src/pages/Office/UnionJoinPage.tsx

hotfix: 공동체 그룹선택 수정
hotfix: 공동체 초대 개선

hotfix: 공동체 그룹선택 수정

---

src/apis/member.ts
src/components/member/MyMember.tsx
src/components/prayCard/NewPrayCardCompletionStep.tsx
src/components/prayCard/NewPrayCardGroupSelectStep.tsx
src/components/prayCard/NewPrayCardIntroStep.tsx
src/components/prayCard/NewPrayCardRequestStep.tsx
src/components/prayCard/PrayRequestItem.tsx
src/pages/Group/GroupJoinPage.tsx
src/pages/GroupPage.tsx
src/pages/PrayCard/PrayCardCreatePage.tsx
src/pages/PrayCard/PrayCardEditPage.tsx
src/stores/baseStore.ts

fix: dnd 버그 수정
refactor: 초대 제한 수정
chore: 만료 안내 수정

fix: dnd 버그 수정

---

package-lock.json
package.json
src/App.tsx
src/mock/GroupPageMock.tsx
src/mock/mockApiFunctions.ts
src/mock/mockData.ts
src/pages/AdminPage/AdminPage.tsx
src/pages/AdminPage/NewAdminPage.tsx
src/pages/BibleCardPage/BibleCardGeneratorPage.tsx
src/pages/GroupPage.tsx
src/pages/MainPage.tsx

fix: 관리자 페이지 수정
feat: new admin page 추가

fix: 관리자 페이지 수정

---

package-lock.json
package.json
src/components/profile/PrayCardHistoryList.tsx
src/components/profile/SettingDialog.tsx
src/pages/GroupListPage.tsx

hotfix: 설정 모달 및 그룹원수 수정
0.14.0

hotfix: 설정 모달 및 그룹원수 수정

---

src/components/group/GroupSettingsDialog.tsx
src/components/ui/wheel-picker.tsx

hotfix: reminder wheel picker 수정
hotfix: 모달 포커스 버그 수정

hotfix: reminder wheel picker 수정
