TeamVisioneer/PrayU-Web

src/App.tsx
src/apis/group.ts
src/apis/member.ts
src/components/KakaoShareBtn.tsx
src/components/ui/input.tsx
src/pages/GroupCreatePage.tsx
src/pages/GroupPage.tsx
src/pages/MainPage.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

group 도메인에 필요한 페이지와 컴포넌트들을 이전합니다.
https://www.notion.so/mmyeong/refactor-8d93e6e0be3e45938073cf683a57daee?pvs=4

refactor: goupPage 이전

---

src/apis/prayCard.ts
src/components/member/Member.tsx
src/components/member/MemberList.tsx
src/components/prayCard/PrayCardCreateModal.tsx
src/components/ui/textarea.tsx
src/pages/GroupPage.tsx
src/stores/baseStore.ts

기도제목 작성뷰를 이전합니다.
Member fetch 과정에서 현재 유저가 member 목록에 없을 때 insert 하는 부분이 있었는데
이부분 사이드이펙트가 있을 것 같아 기도제목 작성할 때 Member insert 하도록 수정하였습니다.
기존에 Profiles 로 사용되고 있는 컴포넌트는 일단 통일을 위해 Member 로 가져갔습니다.
(MemberList-Member 구조)
이후에 논의에 따라 Profile 로 통일해도 좋을 것 같습니다.
~~memberList 에 있으면 기도카드만 생성~~
~~없으면 Member, 기도카드 같이 생성~~
https://www.notion.so/mmyeong/refactor-8d93e6e0be3e45938073cf683a57daee?pvs=4

refactor: 기도제목 작성뷰 이전

---

src/apis/prayCard.ts
src/components/member/Member.tsx
src/components/member/MemberList.tsx
src/components/prayCard/PrayCardBtn.tsx
src/components/prayCard/PrayCardCalendar.tsx
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/TodayPrayBtn.tsx
src/stores/baseStore.ts
supabase/types/tables.ts
tailwind.config.js

prayList 드로워를 이전합니다.
PrayCardUI 를 재사용하기 위해 카드를 넘길 때마다 재랜더링 되도록 작성하였는데
이 부분은 이후에 한번에 불러올 수 있도록 수정하면 좋을 것 같습니다.

refactor: prayList 드로워 이전

---

src/apis/pray.ts
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/prayCard/WeeklyCalendar.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

PrayList 의 캐러셀 부분 데이터 관리를 재정의 합니다.
todayPrayTypeHash[prayCardId] 를 통해 전역 변수를 동적으로 할당하여 관리할 수 있도록 합니다.
https://www.notion.so/mmyeong/refactor-8d93e6e0be3e45938073cf683a57daee?pvs=4

refactor: PrayCardList 데이터 관리

---

src/components/member/Member.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionBtn.tsx

(스크롤 사진도 캡쳐하려 했는데 힘드네용ㅠ)
https://www.notion.so/mmyeong/fix-c8a472f11ecd4b70afa33b4a18cc1768?pvs=4

fix: 기도제목 길어졌을 때 scroll처리, 줄바꿈 처리

---

src/components/GroupMenuBtn.tsx
src/pages/GroupPage.tsx

db 를 건드린 탓에 그룹메뉴 렌더링에서 에러가 발생했습니다. 이를 해결하고자 fetch 해 온 groupList 의 원소 중 null 인 값에 대해서는 a 태그를 생성하지 않도록 분기처리 하였습니다.

fix: 그룹메뉴 생성 에러 해결

---

src/apis/prayCard.ts
src/components/member/MyMember.tsx
src/components/member/OtherMemberList.tsx
src/components/prayCard/PrayCardCreateModal.tsx
src/components/prayCard/PrayCardList.tsx
src/lib/utils.ts
src/pages/GroupPage.tsx
src/stores/baseStore.ts

이제 7일 이내의 기도제목 카드만 올라옵니다.
생성한지 7일 지나면 다시 작성뷰로 넘어갑니다.

refactor: 기도제목 7일 필터 및 작성 예외처리

---

src/components/prayCard/PrayCardUI.tsx

fix: textarea 내 기도제목으로 나오는 버그 수정

---

src/App.css
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx
src/pages/GroupCreatePage.tsx

https://www.notion.so/mmyeong/fix-QA-426f9724969b4a5684b33569462ca4c0?pvs=4

chore: QA 반영

---

src/apis/member.ts
src/components/prayCard/WeeklyCalendar.tsx
src/lib/utils.ts

위와 같이 00시 -09시 사이에 생성된 카드에 대해서
기도 날짜가 하루 전 부터 시작하는 버그를 수정합니다.

chore: Calendar 버그 수정

---

src/components/prayCard/PrayCardCreateModal.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/pages/GroupCreatePage.tsx
src/stores/baseStore.ts

생성버튼을 여러번 클릭했을 때 나는 다중생성 문제를 해결합니다.
생성 버튼 클릭 핸들링 함수에서 비활성화 상태를 관리합니다.
→ 기도 카드와 그룹 생성 테스트 과정에서 기존과 다르게 하나씩 생성되는 것을 확인하였습니다.

fix: 생성버튼 비활성화 상태 관리

---

src/Enums/prayType.ts
src/apis/prayCard.ts
src/components/member/MyMember.tsx
src/components/member/OtherMember.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/prayCard/WeeklyCalendar.tsx
src/components/todayPray/TodayPrayStartCard.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

https://www.notion.so/mmyeong/feat-35d765e263db416a88ad1854078f7de3?pvs=4

feat: 내 기도제목에서 반응 개수 확인하기

---

src/components/group/GroupBody.tsx
src/components/member/MemberInviteCard.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMemberList.tsx
src/components/prayCard/PrayCardUI.tsx
src/pages/GroupPage.tsx

기도카드 생성뷰에서 그룹 초대 카드가 같이 노출되고 있는 부분을 해결합니다.
원인: 기도카드 생성은 MyMember 에서 관리하고 그룹초대는 groupPage 에서 관리하면서 나타난 엣지 케이스
해결: 
1. 그룹 입장 관련은 GroupBody 에서 분기처리 ( 기도카드 작성, 그룹 초과 )
2. MemberList 노출 관련은 OtherMemberList 에서 분기처리 ( 오늘의 기도카드, 멤버 초대카드 )
[앞에 2개: 그룹 입장 관련], [뒤에 2개: Member 관련]
https://www.notion.so/mmyeong/refactor-GroupBody-6e274f174bd04c66a107021c22b8faf7?pvs=4

refactor: GroupBody 분리 및 MemberList 분기처리

---

src/components/member/MyMember.tsx

안드로이드 카카오 인앱 브라우저에서 기도제목 수정에서 화면 렌더링이 원활하지 않던 부분을 수정했습니다.
https://www.notion.so/mmyeong/fix-2356e07cb2c5433c9c1c0225a3504fd2?pvs=4

fix: 안드로이드 drawer rendering 해결

---

src/apis/prayCard.ts
src/components/member/MyMember.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionWithCalendar.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

- PrayCardUI가 너무 복잡합니다.
- 남의 기도제목이 길 때 윗부분이 잘립니다.
- MyMember에서 받은 prayCard 데이터로 불필요한 useEffect를 없애도 되는 상황입니다.
https://www.notion.so/mmyeong/refactor-PrayCardUI-b5a32be59f31466ea8433c5d8a526a4a?pvs=4

refactor: PrayCardUI >  MyPrayCard 분리 + 기도제목 잘림 이슈 해결

---

src/apis/prayCard.ts
src/components/member/OtherMemberList.tsx
src/components/prayCard/PrayCardList.tsx
src/stores/baseStore.ts

기도를 완료한 카드는 오늘의 기도에서 노출되지 않도록 하였습니다.
https://www.notion.so/mmyeong/fix-PrayCardList-16949caca1094311ba2e4442cfb9cbd0?pvs=4

refactor: prayCardList 기도 필요카드만 노출

---

package-lock.json
package.json
src/App.tsx
src/apis/group.ts
src/apis/member.ts
src/apis/pray.ts
src/apis/prayCard.ts
src/components/KakaoShareBtn.tsx
src/main.tsx
src/pages/GroupCreatePage.tsx
src/stores/baseStore.ts
vite.config.ts

운영환경에 센트리 세팅을 추가합니다.
이제 staging 과 prod 를 구분하여 에러를 보고받을 수 있습니다.
https://www.notion.so/mmyeong/build-Sentry-16533eed54014f6586dbe2e474b13aec?pvs=4
https://visioneer.sentry.io/

build: Sentry 세팅

---

src/components/member/OtherMemberList.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/PrayCardUI.tsx
src/pages/GroupPage.tsx

https://www.notion.so/mmyeong/fix-920e1c75d42c494486f00e94edfc63e8?pvs=4
fix: prayCardUI content left top
fix: member number added right on group name
fix: delete isOverFlow status

fix: 그룹명 옆 멤버수 표시 && 기도내용 좌상단 배치

---

package-lock.json
package.json
src/App.tsx
src/analytics/amplitude.d.ts
src/analytics/analytics.ts
src/components/GroupMenuBtn.tsx
src/components/KakaoShareBtn.tsx
src/components/member/MemberInviteCard.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMember.tsx
src/components/member/OtherMemberList.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/PrayCardCreateModal.tsx
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/prayCard/ReactionWithCalendar.tsx
src/components/todayPray/MyMemberBtn.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/components/todayPray/TodayPrayStartCard.tsx
src/pages/GroupCreatePage.tsx
src/pages/GroupPage.tsx
src/stores/baseStore.ts
tsconfig.app.json

.env에 VITE_AMPLITUDE_API_KEY 추가했습니다!
- 언더바(_) 검색 가능이 가능해서 사용하였습니다.
- 각 이벤트 별 들어가는  property는 노션에 정리하였습니다.
- property 이름은 카멜 대신에 _ 사용하였습니다.
- 카카오톡과 관련된 로그인, 로그아웃, 공유 버튼 이벤트는 아직 없습니다!
https://www.notion.so/mmyeong/build-amplitude-4db5ced08d274574a1fda2afcb1b969f?pvs=4

build: analytics-amplitude setting

---

src/components/member/MyMember.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/stores/baseStore.ts

https://www.notion.so/mmyeong/feat-f4ad852055c4427a815393b45c7713ff?pvs=4
feat: added MyPrayDrawer direct click
chore: 누군가 내게 기도했어요 added
chore: 수정 버튼 우상단 배치

feat: 기도확인 드로어 바로 연결 && 수정 버튼 우상단 배치

---

index.html
src/components/member/MemberInviteCard.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMember.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/PrayCardCreateModal.tsx
src/components/prayCard/PrayCardList.tsx
src/components/share/KakaoShareBtn.tsx
src/components/todayPray/TodayPrayStartCard.tsx
src/lib/utils.ts
src/pages/GroupCreatePage.tsx
src/pages/MainPage.tsx

https://www.notion.so/mmyeong/fix-pray_summary-c00eee558e5a4eadb7f6fc89def3d86e?pvs=4
fix: ‘누군가 내게 기도했어요’ 멘트 기도가 0개이면 출력하지 않기
fix: summary 반응형 고려해서 최대 수치 정하기
fix: 멘트 수정( 토스체 )

fix: 내 기도반응 클릭 분기처리 && praySummary 동적 한줄 제한 && 토스체(친절, 친구, 보아요, 띄어쓰기)

---

src/components/group/GroupBody.tsx
src/components/member/OtherMember.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx

height 고정값으로 사용하고 있던 부분 전수조사 후 스크롤 및 깨짐 처리하였습니다.
1. Drawer 길이를 조정할 때는 내부 첫번째 컨텐츠 길이를 min-h-[0vh], max-h-[0vh] 값으로 조정한다.
-> 최소가 없으면 줄어들고, 최대가 없으면 스크롤이 안생긴채 늘어납니다.
3. 컨텐츠 내에 있는 컴포넌트들은 flex-grow min-h-full max-h-full 로 관리한다
(h-full 은 부모 컴포넌트에 포함된 것이 하나일 때만 유의미 합니다. 두개 이상일 때는 flex-grow 를 통해서 최대 길이를 맞춥니다.)

fix: height 관련 이슈 처리

---

src/components/member/OtherMember.tsx
src/components/member/OtherMemberList.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionWithCalendar.tsx
src/components/prayCard/WeeklyCalendar.tsx

null 값으로 넘어오는 데이터들에 대해 디버깅이 되지 않아 null 타입을 최소화 하는 것을 목표합니다.
기존 PrayCardUI 의 사용이 혼재되면서 
(1) 데이터가 추가로 불러오는 이슈
(2) null 타입을 같이 들고 오면서 예외사항 발생하는 이슈
를 해결하고자 PrayCardUI 를 분리합니다.
PrayCardUI 를 (1) 오늘의 기도, (2) 개별 기도카드 에서 사용
PrayCardUI는 오늘의기도에서 사용, 
OtherPrayCardUI 는 개별 기도카드에서 사용
ExpiredPrayCardUI 는 만료된 멤버 대상 개별 기도카드로 사용

refactor: PrayCardUI 분리

---

src/apis/pray.ts
src/apis/prayCard.ts
src/components/member/MyMember.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/prayCard/PrayCardList.tsx
src/components/prayCard/PrayCardUI.tsx
src/components/prayCard/ReactionWithCalendar.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

중복 패칭 부분과 null 관련 부분을 해결합니다.
PrayData 를 직접 Fetch 하던 부분을 제거하고
PrayCard.pray 를 통해 prayData를 사용합니다.
https://www.notion.so/mmyeong/refactor-PrayCard-pray-8c120ab3f1f34cbfb2cb7e7da0c8f509?pvs=4

refactor: prayData 제거 및 PrayCard.pray 사용

---

src/components/prayCard/PrayCardCreateModal.tsx
src/pages/MainPage.tsx

fix: MainPage Btn 수정 && 기도카드 생성 재시도 환경

---

src/components/member/OtherMemberList.tsx

모든 멤버의 기도카드가 만료되어도 오늘의기도 노출(오늘의 기도 안한 상태). 막상 들어가면 초대하라고 뜸(오늘의 기도 진행 불가)
모든 맴버의 기도카드가 만료되었을 때는 멤버리스트로 보여줌

fix: 오늘의 기도 예외처리

---

src/components/group/GroupBody.tsx
src/components/member/MemberInviteCard.tsx
src/components/member/MyMember.tsx
src/components/member/OtherMember.tsx
src/components/member/OtherMemberList.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/todayPray/TodayPrayStartCard.tsx
src/stores/baseStore.ts

OtherMember에 Drawer 가 포함되어 있어서 Member 수만큼 Drawer 가 생성되고 있던 부분을 수정합니다.
OtherMemberList 에서  Drawer 를 생성하고 OtherMember 가 클릭될 때 올라오도록 합니다.
클릭 될 때 otherMember 전역변수를 바꿔주면서 내부 컨텐츠가 동적으로 변하도록합니다.
https://www.notion.so/mmyeong/refactor-otherMember-Drawer-c84f85dd01a64cafae6b717b7e3a30ad?pvs=4

refactor: OtherMemberDrawer 전역 사용

---

src/components/pray/PrayListDrawer.tsx
src/pages/GroupCreatePage.tsx
src/pages/GroupPage.tsx

그룹명 길이를 12자로 제한하고 깨지는 부분 수정합니다.

hotfix: 그룹명 길이 제한

---

src/components/member/MyMember.tsx
src/components/member/MyMemberBtn.tsx
src/components/member/OtherMember.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/components/prayCard/ReactionBtn.tsx
src/components/share/OpenContentDrawerBtn.tsx
src/components/share/OpenShareDrawerBtn.tsx
src/components/share/ShareDrawer.tsx
src/components/todayPray/TodayPrayBtn.tsx
src/components/ui/drawer.tsx

history.pushState 를 통해 안드로이드 백키 문제를 해결합니다.
`드로워 오픈 때`
-> history.pushState 를 통해 url 히스토리에 더미 URL(그룹 페이지 URL) 추가
`뒤로가기 버튼 클릭시 `
-> Draw 내에서 popstate 이벤트 헨들링을 통해 드로워 닫기 ( 기본 뒤로가기는 진행되나 더미 URL 에서 기본 URL 로 돌아가는 식으로 동작)
`스와이프나 딤배경 클릭하여 드로워 닫을 때`
-> 더미 URL 남은 채로 서비스 이용 ( 오히려 서비스 이탈을 막을 수 있음 )

fix: Drawer backwardKey 이슈

---

src/components/group/GroupMenuBtn.tsx
src/components/member/MemberInviteCard.tsx
src/components/member/OtherMember.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/share/ShareDrawer.tsx
src/components/todayPray/TodayPrayCardUI.tsx
src/components/todayPray/TodayPrayStartCard.tsx
src/pages/MainPage.tsx

https://www.notion.so/mmyeong/fix-ea072dfaac1542649152187220b5cb7d?pvs=4

fix: 카톡 프사 비율 수정 + 캐러셀 온보딩 잘 보이게

---

src/components/pray/PrayList.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx
src/components/share/ContentDrawer.tsx
src/components/share/KakaoShareBtn.tsx
src/components/share/ShareDrawer.tsx
src/components/todayPray/TodayPrayCardList.tsx

->  카카오톡 공유 메세지의 타이틀에 그룹명을 추가합니다.
-> 카카오 공유 확인
-> 초대 및 말씀 공유 동작 확인

reafactor: 카카오 공유시 그룹명 추가

---

src/components/group/GroupMenuBtn.tsx
src/pages/GroupCreatePage.tsx

1. 그룹 생성 후 기도제목 작성으로 이동 중 sheet가 사라지지 않는 문제.
useNavigate -> window.location.href 로 페이지 이동 함수를 바꿔 해결.
2. 그룹 생성 페이지 이미지 개선
https://www.notion.so/mmyeong/fix-sheet-a7c7812fd191447c86ca7f182b1f40c6?pvs=4
fix: sheet navigae error solved
fix: useNavigate import delete in GroupMenuBtn.tsx

fix: 그룹 생성후 시트 에러 및 이미지 개선

---

src/components/prayCard/MyPrayCardUI.tsx
src/components/share/ContentDrawer.tsx

min-h-00 값이 들어가면 안드로이드에서는 다르게 동작하는 것 같습니다.
이전처럼 h-00 방식으로 수정합니다.

fix: Android drawer Height 문제 수정

---

src/components/group/GroupMenuBtn.tsx
src/components/prayCard/PrayCardCreateModal.tsx
src/pages/GroupCreatePage.tsx

메타 광고를 돌리면서 그룹 생성을 처음에 하는 사람이 많아졌는데
들어와서 그룹 생성 이후 기도제목 작성 페이지에서 이탈을 많이 하고 있습니다.
그룹 생성하면 바로 그룹 페이지로 들어오도록 수정합니다.
https://www.notion.so/mmyeong/group-member-prayCard-09f88acb8e294c4aa302697c17c5ce49?pvs=4

hotfix: group 생성시 member, prayCard 생성

---

package-lock.json
src/components/alert/DefaultAlert.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/pages/MainPage.tsx
src/stores/baseStore.ts

- ~~> 페이드 유저가 메인페이지에서 이탈이 많아 카카오 로그인 과정을 변경합니다.
-> 카카오 로그인 버튼 첫 클릭시 카카오톡에서 열기 창이 노출됩니다.~~
~~기존 카카오브라우저 이외의 경우 카카오 로그인 버튼 아래 딥링크 버튼 고정
변경 첫 접속 때는 카카오 로그인 버튼 누를때 딥링크 실행, 카카오 로그인 버튼 재클릭시 로그인 진행~~

revert: 딥링크 제거

---

src/App.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx
src/components/share/ContentDrawer.tsx
src/components/share/KakaoInit.tsx
src/components/share/KakaoShareBtn.tsx
src/components/share/ShareDrawer.tsx
src/components/todayPray/TodayPrayCardList.tsx
src/pages/MainPage.tsx

카카오 버튼이 눌릴 때마다 카카오 스크립트를 load 하고있어서 버튼 응답속도가 느렸던 문제를 해결합니다.
추후 카카오 메세지 관련해서도 스크립트를 사용하기 때문에 App 컴포넌트에서 한번만 로드하도록 합니다.

refactor: 카카오 공유 스크립트 분리

---

src/apis/prayCard.ts
src/components/group/GroupBody.tsx
src/components/member/MyMember.tsx
src/components/prayCard/MyPrayCardUI.tsx
src/pages/PrayCardCreatePage.tsx

member.updated_at 에만 의존해서 기도카드 생성을 분기처리하는 문제를 수정합니다.
groupBody 에서 member.updated_at 으로 분기처리
1. groupBody 에서는 멤버 유무 및 업데이트로 분기처리
2. MyMember 에서 카드 생성일자로 분기처리

refactor: Mymember 에서 prayCard 생성 분기처리

---

src/components/prayCard/OtherPrayCardUI.tsx

만료카드가 노출 될 때 PrayCardUI 도 같이 생성되고 있어서 예외처리 합니다.

hotfix: 만료카드 예외처리

---

src/components/prayCard/OtherPrayCardUI.tsx

만료된 기도카드가 리턴 되기 전에 OtherPrayCard 를 fetch 하고 있어서 예외처리합니다.

hotfix: 만료카드 예외처리-re

---

src/components/kakao/Kakao.d.ts
src/components/kakao/KakaoCallback.tsx
src/components/kakao/KakaoController.tsx
src/components/kakao/KakaoTokenRepo.ts
src/components/prayCard/MyPrayCardMenuBtn.tsx
src/components/todayPray/TodayPrayBtn.tsx

카카오톡 메세지 기능을 활용하여 기도제목 공유 기능을 구현합니다.
현재는 임의의 이미지로 메세지가 가지만 이후에는 동적으로 본인 메세지를 이미지로 생성해서 보내도 좋을 것 같습니다.

feat: 기도제목 공유 메세지 구현

---

src/components/group/GroupMenuBtn.tsx
src/components/kakao/KakaoTokenRepo.ts

카카오 토큰 관련 이슈가 생기면 쿠키를 날려야 하기 때문에
로그아웃에 쿠키 제거 로직을 추가하여 이슈가 있을 경우 로그아웃을 유도합니다.

fix: 로그아웃에 카카오 쿠키 정보 초기화

---

src/App.tsx
src/apis/group.ts
src/components/group/GroupBody.tsx
src/components/group/GroupMenuBtn.tsx
src/components/member/MyMember.tsx
src/pages/GroupNotFoundPage.tsx
src/pages/GroupPage.tsx
src/pages/GroupRedirectPage.tsx
src/pages/PrayCardCreatePage.tsx
src/stores/baseStore.ts

1. 기도제목 작성 페이지를 독립적으로 사용할 수 있도록 변경합니다.
1. 작성페이지에서 새로고침 가능
2. 다음에 작성하기 추가
2. 그룹페이지 리다이렉트 과정을 수정합니다.
1. 404 페이지 만들기
2. /group 분리

refactor: PrayCard 생성 페이지 경로 변경

---

src/apis/user.ts
src/components/member/OtherMemberList.tsx
src/components/prayCard/DeletedPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx

api를 통해 기도카드를 fetch할 때 기본적으로 deleted_at 이 null 인 기도카드들만 불러오게끔 돼 있어서 현재 처리한 방식이 '삭제'와 관련해 타 도메인(ex.만료)과 독립적이지 않을 수 있습니다. 추후 api 함수 개선, 데이터베이스 개선 등의 리팩토링 과정에서 이 부분도 다시 고려돼도 좋을듯합니다.
fix: deleteUser api 호출함수 data, error, sentry 추가
feat: 멤버들 기도카드 모두 삭제된 경우 분기 처리
feat: DeletedPrayCardUI

fix: 기도카드 모두 삭제된 멤버리스트 보여주기

---

src/apis/member.ts
src/apis/prayCard.ts
src/apis/user.ts

회원 탈퇴와 관련해 이전에 api 로직에서 not 연산을 쿼리문에서 사용하였는데 인덱싱 저하를 일으켜 not 연산자 뺐습니다.
회원 탈퇴 시 해당 유저와 관련된 member, pray, prayCard 들을 soft delete처리하는 과정을 deleteUser 함수에 추가했습니다.
기존에는 탈퇴된 유저를 거르는 것을 not이 했는데 이제는 해당 유저의 행적들을 deleted_at == NULL 을 통해 확인합니다.
https://www.notion.so/mmyeong/refactor-api-3eb6706808564083b374c3929c957416?pvs=4

fix: 쿼리 not 연산자 삭제 && 회원 탈퇴 api deleted_at 추가

---

src/components/ui/button.tsx
src/pages/PrayCardCreatePage.tsx

기존의 다음에 작성하기가 밑줄로 되어 있어서 버튼으로 바꿨습니다.
https://www.notion.so/mmyeong/feat-258c8195886a433e8c1ca0fad87e1930?pvs=4

fix: 다음에 작성하기 버튼 강조

---

src/components/pray/PrayList.tsx
src/components/share/ContentDrawer.tsx
src/components/share/ShareDrawer.tsx
src/components/todayPray/TodayPrayCardListDrawer.tsx
src/pages/GroupCreatePage.tsx
src/pages/MainPage.tsx
src/pages/MyProfilePage.tsx

https://www.notion.so/mmyeong/fix-5e11389d1aae4b89910303cceecf749e?pvs=4

fix: <img>상위 컴포넌트 css에 object-cover 추가

---

.github/workflows/deploy_prod.yaml
src/components/prayCard/DeletedPrayCardUI.tsx
src/components/prayCard/DummyPrayCardUI.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/components/todayPray/TodayPrayCardUI.tsx

드로어에 있는 기도카드 내용부분을 스와이프 가능하게 했습니다.
Drawer 내부에서 스와이프 필요한 기도카드UI 들을 다 p 태그로 바꿨습니다.
다만 MyPrayCardUI는 일단 놔뒀습니다.
https://www.notion.so/mmyeong/fix-5652cf053abb40c6a9716b1a0bbf6822?pvs=4

hotfix: 드로어 내 기도카드 내용 Textarea -> p 태그로 변경

---

src/App.tsx
src/components/pray/PrayList.tsx
src/components/prayCard/DeletedPrayCardUI.tsx
src/components/prayCard/ExpiredPrayCardUI.tsx
src/components/share/ContentDrawer.tsx
src/components/share/KakaoShareBtn.tsx
src/components/share/KakaoShareCallBack.tsx
src/components/share/OpenShareDrawerBtn.tsx
src/components/share/ShareDrawer.tsx
src/components/todayPray/TodayPrayCardListDrawer.tsx

초대 카드의 각 역할에 맞춰 이미지와 멘트를 수정합니다.
이후 이미지는 디자이너 기준으로 추가 수정합니다.
1. 카카오 공유 버튼 리팩터링
2. 커스텀 메세지 컴포넌트 추가
3. 사용처 업데이트
4. 카카오 전송완료 콜백 추가

refactor: 카카오 공유 메세지 개선

---

src/App.tsx
src/components/auth/LogInDrawer.tsx
src/components/auth/LoginRedirect.tsx
src/pages/EmailLoginPage.tsx
src/pages/TermServicePage.tsx

로그인 종류가 많아지면서 로그인 이후 redirect 하는 지점이 명시되지 않아 혼동이 있습니다.
/login-redirect 라는 경로를 만들고 동의를 안한 유저만 /term 으로 넘기도록 합니다.

refactor: 로그인 리다이렉트 페이지 추가

---

src/components/auth/LoginRedirect.tsx
src/components/kakao/Kakao.d.ts
src/components/kakao/KakaoController.tsx
src/components/kakao/KakaoTokenRepo.ts
src/components/prayCard/MyPrayCardMenuBtn.tsx
src/stores/baseStore.ts

카카오 로그인 처음 할 때 소셜 기능 관련 선택 동의가 가능한 것 같아 그에 맞게 수정합니다.
이후 카카오 메세지 관련 기획이 들어간다면 이를 활용할 수 있는 토대를 마련합니다.

refactor: 카카오톡 이용중 동의 개선

---

src/components/member/OtherMemberDrawer.tsx
src/components/member/OtherMemberList.tsx
src/components/prayCard/DeletedPrayCardUI.tsx
src/components/todayPray/TodayPrayCardList.tsx
src/components/todayPray/TodayPrayCompletedItem.tsx
src/components/todayPray/TodayPrayDummyCompletedItem.tsx
src/components/todayPray/TodayPrayEmptyItem.tsx
src/pages/GroupPage.tsx

refactor: 멤버 드로워 분리 및 개선

---

src/components/kakao/KakaoCallback.tsx
src/components/kakao/KakaoTokenRepo.ts
src/components/todayPray/TodayPrayBtn.tsx
src/components/todayPray/TodayPrayCardList.tsx
src/components/todayPray/TodayPrayCardUI.tsx
src/stores/baseStore.ts

카카오톡 리다이렉트 부분은 라우팅만 하는 곳으로, 
로그인 리다이렉트 부분은 profile 을 업데이트 하는 부분으로 확실히 역할을 분할합니다.

fix: kakaoLogin Redirect

---

src/apis/group.ts
src/components/auth/LoginRedirect.tsx
src/components/kakao/KakaoCallback.tsx
src/components/kakao/KakaoController.tsx
src/components/kakao/KakaoMessage.ts
src/pages/PrayCardCreatePage.tsx
src/pages/TermServicePage.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

카카오톡 메세지가 선택 동의 처리 됨에 따라 
그룹원이 입장했을 때 카카오톡 메세지로 그룹장에게 알림을 주는 기능을 구현합니다.

feat: 그룹 입장 메세지 알림 추가

---

src/components/auth/LogInDrawer.tsx

기존에 ios 앱일 때만 이메일 로그인이 보였는데,
안드로이드 테스터 계정 제공을 위해
앱일 때에는 이메일 로그인이 보이도록 userAgent 를 수정하였습니다!
https://www.notion.so/mmyeong/feat-1f67d57f17844de4934a34043b6ab308?pvs=4

hotfix: 앱일 때, 이메일 로그인 추가

---

src/components/group/GroupMenuBtn.tsx

앱에서 가끔 PrayU 소식을 눌렀을 때 잘 들어가지는 이슈가 있었습니다.
(PrayU 문의를 먼저 눌러본 상태라면 PrayU 소식이 들어가졌습니다.)
이유를 찾다가 주소의 url이 http로 되어 있음을 발견하여 https 로 수정하였습니다.
(App에서 http 통신이 안됨)

hotfix: 카카오 소식 url http -> https 로 수정

---

src/apis/notification.ts
src/components/notification/NotificationBtn.tsx
src/components/notification/NotificationItem.tsx
src/components/notification/NotificationList.tsx
src/components/ui/card.tsx
src/components/ui/popover.tsx
src/components/ui/tabs.tsx
src/pages/GroupPage.tsx
src/stores/baseStore.ts
supabase/types/tables.ts

안읽은 알림과 읽은 알림을 구분하여 feching 합니다.
안읽음 UI 를 정의하고 눌렀을 때 읽음 처리 합니다.

feat: 안읽은 알림 패칭

---

src/apis/notification.ts
src/components/notification/NotificationBtn.tsx
src/components/notification/NotificationList.tsx
src/pages/GroupPage.tsx
src/stores/baseStore.ts

더보기를 통해 페이지 네이션을 진행합니다.
userNotificationView 라는 전역변수를 만들고 notificationList 를 누적하여 받아옵니다.

faet: 알림 페이지 네이션 구현

---

src/components/group/GroupMenuBtn.tsx
src/components/member/OtherMember.tsx
src/components/member/OtherMemberDrawer.tsx
src/components/member/OtherMemberList.tsx
src/components/notification/NotificationBtn.tsx
src/components/prayCard/OtherPrayCardUI.tsx
src/pages/GroupPage.tsx
src/pages/MainPage.tsx
src/pages/Open/UnionWorshipPage.tsx

로그인 드로워 예외처리 필요한 부분 적용합니다.
오늘의 기도 시작 카드 대신 멤버리스트가 뜨도록 해두었는데 괜찮으면 적용하겠습니다.

refactor: UnionWorship 페이지 로그인 예외 처리

---

src/components/ui/dialog.tsx
src/components/ui/drawer.tsx
src/components/ui/popover.tsx
src/components/ui/sheet.tsx

pushState 가 중복으로 들어가지 않도록 합니다.
아직 문제가 있지만 우선처리합니다.
문제1. 드로워 열고 뒤로가기로 닫지 않을 경우 최대 1개 경로 push
문제2. 드로워 중첩으로 열고 뒤로가기로 닫을 경우 동시에 두개 다 닫힘

fix: pushState 중복 방지

---

src/components/auth/LogInDrawer.tsx
src/pages/MainPage.tsx

지금 메인 페이지에서 카카오톡 로그인을 하는 비율이 평균 60%정도 되는데, 이를 늘려볼 수 있지 않을까 싶어서
도메인 특성상 강남언니처럼 "정보 보호" 에 관한 멘트로 수정해보았습니다.
https://www.notion.so/mmyeong/feat-409cf437936747cf9126340eab9fa306?pvs=4

chore: login drawer 코멘트 수정

---

src/apis/group.ts
src/components/group/GroupMemberOptionTag.tsx
src/components/group/GroupMemberSettingsBtn.tsx
src/components/group/GroupMenuBtn.tsx
src/components/group/GroupSettingsDialog.tsx
src/stores/baseStore.ts

그룹장 관련 이슈를 겪는 고객이 있어 내용 반영합니다.
기존에 그룹장이 그룹을 나가게 되면 그룹장이 부재하는 상황이 있었는데 이를 해결합니다.
그룹장이 그룹을 나가는 경우를 예외처리하고 그룹장 양도 기능을 추가합니다.

feat: 그룹장 양도 기능 추가
